name: gict
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - aiodns=3.5.0=py310haa95532_1
  - aiohappyeyeballs=2.6.1=py310haa95532_0
  - aiohttp=3.13.2=py310h02ab6af_0
  - aiosignal=1.4.0=py310haa95532_0
  - annotated-types=0.6.0=py310haa95532_1
  - anyio=4.10.0=py310haa95532_0
  - async-timeout=4.0.3=py310haa95532_0
  - attrs=25.4.0=py310haa95532_2
  - biopython=1.85=py310h071892a_0
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotlicffi=1.0.9.2=py310h885b0b7_2
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.10.5=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.2.1=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dataclasses-json=0.6.7=py310haa95532_0
  - distro=1.9.0=py310haa95532_0
  - exceptiongroup=1.3.0=py310haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozenlist=1.8.0=py310h885b0b7_0
  - greenlet=3.2.4=py310h73ae2b4_1
  - h11=0.16.0=py310haa95532_1
  - httpcore=1.0.9=py310haa95532_0
  - httpx=0.28.1=py310haa95532_1
  - httpx-sse=0.4.0=py310haa95532_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=py310haa95532_0
  - jiter=0.6.1=py310hefb1915_0
  - jsonpatch=1.33=py310haa95532_1
  - jsonpointer=3.0.0=py310haa95532_0
  - kiwisolver=1.4.9=py310h1e1005b_1
  - krb5=1.21.3=hdf4eb48_0
  - langchain-openai=0.3.16=py310haa95532_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libboost=1.86.0=h9dfe17d_4
  - libboost-python=1.86.0=py310hfb7dd09_4
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.86.1=hd9c3897_1
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libpq=18.0=h063c6db_0
  - librdkit=2025.09.1=h0cb3073_1
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.4=hfa2b4ca_0
  - marshmallow=3.19.0=py310haa95532_0
  - matplotlib-base=3.10.7=py310h0bdd906_0
  - mkl=2025.3.0=hac47afa_454
  - multidict=6.7.0=py310h02ab6af_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.0.0=py310haa95532_0
  - networkx=3.4.2=pyh267e887_2
  - openai=1.109.1=py310haa95532_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.5.4=h725018a_0
  - orjson=3.10.14=py310h636fa0f_0
  - pandas=2.3.3=py310hed136d8_1
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py310hfb50504_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - propcache=0.3.1=py310h827c3e9_0
  - pthread-stubs=0.4=h0e40799_1002
  - pycairo=1.28.0=py310h765e14b_1
  - pycares=4.10.0=py310he29e43d_0
  - pycparser=2.23=py310haa95532_0
  - pydantic=2.12.3=py310haa95532_0
  - pydantic-core=2.41.4=py310h114bc41_0
  - pydantic-settings=2.10.1=py310haa95532_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - qhull=2020.2=hc790b64_5
  - rdkit=2025.09.1=py310h62ce3ce_1
  - regex=2025.9.1=py310h02ab6af_0
  - reportlab=4.4.4=py310h29418f3_0
  - requests=2.32.5=py310haa95532_1
  - requests-toolbelt=1.0.0=py310haa95532_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - seaborn=0.13.2=py310haa95532_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.0=py310haa95532_0
  - sqlalchemy=2.0.44=py310h29418f3_0
  - tbb=2022.3.0=hd094cb3_0
  - tiktoken=0.9.0=py310h8ecf97c_0
  - tk=8.6.13=h2c6b04d_2
  - tqdm=4.67.1=py310h9909e9c_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=py310haa95532_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_inspect=0.9.0=py310haa95532_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=16.0.0=py310h29418f3_1
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=py310haa95532_1
  - winloop=0.3.1=py310h913537a_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=he774522_0
  - yarl=1.22.0=py310h02ab6af_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstandard=0.24.0=py310he335c29_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - annotated-doc==0.0.4
      - backoff==2.2.1
      - bcrypt==5.0.0
      - build==1.3.0
      - cachetools==6.2.1
      - chromadb==1.3.4
      - coloredlogs==15.0.1
      - dotenv==0.9.9
      - durationpy==0.10
      - fastapi==0.121.1
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fsspec==2025.10.0
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - httptools==0.7.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kubernetes==34.1.0
      - langchain==0.3.27
      - langchain-core==0.3.79
      - langchain-text-splitters==0.3.11
      - langgraph-checkpoint==3.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.42
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mmh3==5.2.0
      - mpmath==1.3.0
      - numpy==1.26.4
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-grpc==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - packaging==24.2
      - posthog==5.4.0
      - protobuf==6.33.1
      - pubchempy==1.0.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pygments==2.19.2
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dotenv==1.2.1
      - referencing==0.37.0
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.1.2
      - shellingham==1.5.4
      - starlette==0.49.3
      - sympy==1.14.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.1
      - transformers==4.57.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - urllib3==2.3.0
      - uvicorn==0.38.0
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - zipp==3.23.0
prefix: F:\anaconda3\envs\gict
